#define PERFECT_LOWH 380
#define PERFECT_LOWV 240
#define PERFECT_MIDH PERFECT_LOWH*2
#define PERFECT_MIDV PERFECT_LOWV*2
#define PERFECT_HIGHH PERFECT_LOWH*3
#define PERFECT_HIGHV PERFECT_LOWV*3
#define PERFECT_FULLH PERFECT_LOWH*5
#define PERFECT_FULLV PERFECT_LOWV*5
#define PERFECT_ULTRAH PERFECT_LOWH*10
#define PERFECT_ULTRAV PERFECT_LOWV*10
#define PERFECT_ULTRA2W PERFECT_ULTRAH*20
#define PERFECT_ULTRA2H PERFECT_ULTRAV*20
#define PERFECT_LOW PERFECT_LOWH, PERFECT_LOWV
#define PERFECT_MID PERFECT_MIDH, PERFECT_MIDV
#define PERFECT_HIGH PERFECT_HIGHH, PERFECT_HIGHV
#define PERFECT_FULL PERFECT_FULLH, PERFECT_FULLV
#define PERFECT_ULTRA PERFECT_ULTRAH, PERFECT_ULTRAV
#define PERFECT_ULTRA2 PERFECT_ULTRA2W, PERFECT_ULTRA2H